# ==============================
# SERVER
# ==============================
server.port=8080

# ==============================
# DATABASE - Supabase PostgreSQL
# ==============================
# Substitua com suas credenciais do Supabase:
# Project Settings > Database > Connection String (JDBC)

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.btiyteqfytudpbswxgzd&sslmode=require
spring.datasource.username=postgres.btiyteqfytudpbswxgzd
spring.datasource.password=${PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================
# JWT
# ==============================
# Gere uma chave forte: openssl rand -base64 64
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==============================
# CORS
# ==============================
cors.allowed-origins=http://localhost:4200,http://localhost:4201

# ==============================
# MERCADO PAGO
# ==============================
mp.access-token=${MP_ACCESS_TOKEN}

# ==============================
# Email Brevo SMTP vai substituir quando o cliente tiver email com dominio proprio
# ==============================
# Email Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${GMAIL_EMAIL}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

app.frontend-url=${FRONTEND_URL:http://localhost:4200}